# Generated by Django 5.0.2 on 2024-03-19 10:06

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=21)),
                ("file", models.FileField(upload_to="songs/")),
                (
                    "cover",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        default="covers/default.png",
                        force_format="JPEG",
                        keep_meta=True,
                        quality=86,
                        scale=1,
                        size=[225, 225],
                        upload_to="covers/",
                    ),
                ),
                ("text", models.TextField(blank=True, default=None)),
                ("temp", models.PositiveSmallIntegerField(default=0)),
                ("ton", models.CharField(default=None, max_length=6)),
                (
                    "hashtags",
                    models.CharField(blank=True, default=None, max_length=100),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=None, max_length=255, unique=True, verbose_name="URL"
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.author"
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        related_name="blog_posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
