# Generated by Django 5.0.2 on 2024-03-19 10:40

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0002_author_search_vector_songs_search_vector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
