# Generated by Django 5.0.2 on 2024-03-19 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0003_alter_songs_search_vector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
