# Generated by Django 5.0.2 on 2024-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0005_alter_songs_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="URL"),
        ),
    ]
